# Generated by Django 5.2.6 on 2025-09-28 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enen_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enen_management.catagory'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='enen_management.catagory'),
        ),
    ]
