# Generated by Django 5.2.6 on 2025-09-28 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enen_management', '0002_participant_category_alter_event_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='category',
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enen_management.catagory'),
        ),
    ]
