# Generated by Django 5.2.6 on 2025-09-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enen_management', '0003_remove_participant_category_alter_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='Untitled', max_length=70),
        ),
    ]
